### ISSUE TITLE
Vetiver docstrings use "Example" for sections, but it does not get parsed as a numpy example section

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#10]
I think the numpy doc spec technically wants people to write "Examples" with an s, but also w/e does the parsing for sphinx autodoc + numpydoc style appears to be able to handle "Example".

* Should we change the word "Example" to "Examples"?
* Could also raise an issue on griffe and see if it's valuable to add "Example" to the parser / whether they want to require "Examples" verbatim.

Here's an example from [vetiver.pin_metrics](https://rstudio.github.io/vetiver-python/stable/reference/vetiver.pin_metrics.html)

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/2574498/203434806-b080dc2e-8808-4f26-8a23-2c77df35328a.png">

**Comment by isabelizimm** [comment]
I don't mind changing all my **Example** -> **Examples** for vetiver, but for a larger package this could be a large task and a barrier to entry/barrier to a good experience with quartodoc. Since it is not a bug with Sphinx, I would prefer (selfishly) to accept either.

**Comment by machow** [comment]
opened an issue here: https://github.com/mkdocstrings/griffe/issues/118

I think the vetiver docs use sphinx-napolean for parsing. One thing I wonder about is whether sphinx-napolean always escapes chunks of code with `>>>`?
