### ISSUE TITLE
`render_annotation` needs documentation on website

### ISSUE THREAD

**Issue by wch** [machow/quartodoc#100]
The `render_annotation` method needs some documentation on the website to explain what it does, what it takes as input, and what it should return.

**Comment by machow** [comment]
There's now an API entry for this (and other methods on renderer)

https://machow.github.io/quartodoc/api/MdRenderer.render_annotation.html#quartodoc.MdRenderer.render_annotation

(Note that no return type is specified, but there's an issue open for supplying return type annotations)
