### ISSUE TITLE
Docs should explain why quartodoc has to be run separately from `quarto`

### ISSUE THREAD

**Issue by wch** [machow/quartodoc#104]
One thing that is confusing is that `quartodoc` has a section in the `_quarto.yml` file, but `quartodoc` is not actually a quarto extension.

There is a two-step build process to build the documentation for a python module with quartodoc:
- Run `quartodoc build` to generate .qmd files from the .py source files.
- Run `quarto render` to convert the .qmd files to .html

It took me a while to fully understand the consequences of this -- for example, changing the `quartodoc` section of `_quarto.yml` does _not_ trigger a rebuild when `quarto preview` is running.

I've thought about it a bit, and I think it would be clearer if the `quartodoc` configuration was in a separate file from `_quarto.yml`, to make it clear to users that running `quarto` has nothing to do with running `quartodoc`.

**Comment by machow** [comment]
This seems related to..

* https://github.com/machow/quartodoc/issues/29

I think we could trigger a rebuild, if there were a pre-render environment variable indicating that the pre-render was triggered by a change to the `_quarto.yml` file? (cc @cscheid, would love to discuss tomorrow!)

**Comment by wch** [comment]
I'm not 100% convinced that your proposal is the way to go, but I could be convinced. Here are the reservations I have.

If I understand your proposal correctly, the following changes would trigger rebuilding of the relevant portions of the site:

- Modifying the `quartodoc` section of `_quarto.yml`
- Editing one of the `.qmd` files in the generated files (which is not something one would normally do)

But this would _not_ trigger any rebuilding:

- Editing a docstring in one of the source .py files.

In practice, I edited the docstrings in the .py files and wanted to see the resulting html output with `quarto preview`. But with the proposal, there's not really a way to make this work (other than running `quartodoc build` manually).


The second reservation I have is that running `quarto render` or `quarto preview` will update the .qmd and .html files based on whatever version of the package happens to be installed, and its upstream dependencies (if it imports objects which are documented, as is the case with shiny, which imports things from htmltools and documents them on the shiny site). This means that (A) `quarto` will usually have to be run in a venv or something similar. That's not too unreasonable, but another problem is (B) if `quarto` is run on CI, (as we do for the pyshiny website), then python and the correct version of target package must be installed on the CI system. I would like to have the option of generating the .qmd files on my local system, committing them, and then pushing those changes.

**Comment by machow** [comment]
What's the behavior that works best for you here?

**Comment by machow** [comment]
Really helpful point from @wch -- when you change pkgdown.yml, it's a signal that you need to run pkgdown again.

**Comment by machow** [comment]
There's now more dialogue around each command, and an issue tee'd up for providing a "watch" command (https://github.com/machow/quartodoc/issues/114)

https://machow.github.io/quartodoc/get-started/basic-building.html#rebuilding-doc-pages



![Image](https://user-images.githubusercontent.com/2574498/235791815-eb96ab38-c7fc-43db-8890-0144b89b3902.png)
