### ISSUE TITLE
Rendering large file hangs on interlinks

### ISSUE THREAD

**Issue by wch** [machow/quartodoc#111]
Note that I am not 100% sure that this is due to interlinks, but I think is likely.

In this PR, I am consolidating all of the html tag functions into one page: https://github.com/rstudio/pyshiny-site/pull/82

That's about 130 pages combined into a single page. The .qmd file is about 3200 lines.

When I do `quarto render` it hangs; I waited over 15 minutes on an M1 Mac. The same thing happens in GitHub Actions, which you can see here (Note that I canceled it manually):
https://github.com/rstudio/pyshiny-site/actions/runs/4702792119/jobs/8340483675?pr=82#step:9:1315

**Comment by machow** [comment]
Note I double checked trying to build the page without the interlinks filter, and it *does work*. So fingers crossed for the lua version 😬
