### ISSUE TITLE
Displayed signature of function with `*args` has extra `*`

### ISSUE THREAD

**Issue by wch** [machow/quartodoc#117]
This is related to #91 and #102.

For functions that have `*args`, there is an extra `*` in the displayed signature. For example, https://shiny.rstudio.com/py/api/ui.nav.html

<img width="452" alt="image" src="https://user-images.githubusercontent.com/86978/232359378-c19fa012-02a1-4481-b928-c5789e46cfce.png">

The actual signature is (https://github.com/rstudio/py-shiny/blob/95124eec149b691e2f4166086cb2f2ff3b8a51a7/shiny/ui/_navs.py#L90-L96): 

```py
def nav(
    title: TagChild,
    *args: TagChild,
    value: Optional[str] = None,
    icon: TagChild = None,
) -> Nav:
```

**Comment by machow** [comment]
Ah, thanks! I'm going over the different signature cases again. Are there any you would add to this list?

```python
def pos_only(x, /, a, b=2): ...

def kw_only(x, *, a, b=2): ...

def early_args(x, *args, a, b=2, **kwargs): ...

def late_args(x, a, b=2, *args, **kwargs): ...
```

**Comment by machow** [comment]
Just a random note for posterity, sometimes people are weirded out that the star is not in the AST, but this is also how python represents it...

```python
import ast

tree = ast.parse("""
def f(a, *, b): ...
"""
)

ast.dump(tree.body[0])
```

```
FunctionDef(
    name='f',

    # note how the arg representation is very similar to griffe ----
    args=arguments(posonlyargs=[], args=[arg(arg='a')], kwonlyargs=[arg(arg='b')], kw_defaults=[None], defaults=[]),

    body=[Expr(value=Constant(value=Ellipsis))],
    decorator_list=[]
)
```

**Comment by pawamoy** [comment]
With a signature like the following:

```python
def nav(
    title: TagChild,
    *args: TagChild,
    value: Optional[str] = None,
    icon: TagChild = None,
) -> Nav:
```

...it makes sense that Python automatically considers `value` and `icon` to be keyword-only parameters, since positional ones will be eaten by `*args`, so you cannot ever pass `value` or `icon` with positional arguments, only keyword ones.
