### ISSUE TITLE
Hovering over a function in VSCode provides unrendered documentation

### ISSUE THREAD

**Issue by schloerke** [machow/quartodoc#120]
In local development, I can hover over a method with a quarto chunk, it provides a code chunk with untouched quarto comments:

![Screenshot 2023-04-19 at 11 27 45 AM](https://user-images.githubusercontent.com/93231/233141292-5cf7a784-2e72-4739-9c11-42b93644662b.png)

Any suggestion on how to hide these quarto comments when hovering in VSCode?

---------------------------

Current (good/expected) quartodoc output

![Screenshot 2023-04-19 at 12 37 35 PM](https://user-images.githubusercontent.com/93231/233142557-0e1f16e5-7443-4101-b594-8020513d3ad2.png)

I have tried putting the comments as inline options to the cell header:

````
def add_nums(x: float, y: float) -> float:
    """
    Adds two numbers together

    Returns
    -------
    float
        The sum of `x` and `y`.

    Examples
    --------
    ```{shinylive-python, standalone: true, components: [editor, viewer], layout: vertical}
    ## file: app.py
    from mypkg import add_nums
    add_nums(1, 2)

    ## file: requirements.txt
    mypkg
    ```
    """

    return x + y
````

However quartodoc did not render properly:
![Screenshot 2023-04-19 at 12 37 15 PM](https://user-images.githubusercontent.com/93231/233142614-3422befd-be2d-4e27-a353-ae2108751a21.png)

----------------------------

Related... `rstudio/py-shiny` does not display examples on hover, but they are included in the final quartodoc website.

**Comment by wch** [comment]
I don't think you can avoid this -- pyright/pylance don't evaluate any Python code (they only parse it), and they will only show the literal docstrings.

I suggest adding a `_renderer.py` file to handle examples and _add_ the shinylive stuff.

As a side note, the generated type stubs for shinyswatch are quite large because of all the examples, so it might make sense to have the `_renderer.py` script actually generate the examples dynamically.

**Comment by machow** [comment]
Agreed with @wch, that this might be a good place for custom rendering. It seems like the two jobs you have for these examples are:

1. In an IDE, like VS Code, examples show up simply (e.g. no extra formatting, pyshiny-live settings shown)
2. On the doc site, the examples show up in pyshiny-live

It seems like this might let you get both things?:

* put the examples in the simple format needed for (1)
* in a custom quartodoc renderer, try to regex the examples and render them into pyshiny-live format, or something?

But this might be overkill vs just inserting in the examples like shiny does

**Comment by schloerke** [comment]
I'm now inserting the examples like Shiny does.

Thank you!
