### ISSUE TITLE
[Draft] Getting Started Docs

### ISSUE THREAD

**Issue by hamelsmu** [machow/quartodoc#136]
- [ ] Should the user call `quarto create project` to get more of the pages? 
- [ ] We should mention that `quartodoc` will generate separate page for each function/class in this example, but we can change that.
-

**Comment by machow** [comment]
I'm going to close for now, now that there's this tutorial on the homepage (it might not get exactly those things, but hopefully close enough)

https://www.loom.com/share/fb4eb736848e470b8409ba46b514e2ed?sid=f42f0a10-94e3-40b7-a13f-be09adb4144c
