### ISSUE TITLE
Add Rendering Tests

### ISSUE THREAD

**Issue by hamelsmu** [machow/quartodoc#166]
Add tests for rendering in `tests/renderers.py`

**Comment by machow** [comment]
In case it's useful, I added an example of how a person could read an object (and then render it) without having to save out to a file (though, we could keep the examples as files and `{{< include ... >}}` them, etc.. if it's easier):

* https://github.com/machow/quartodoc/issues/163

**Comment by machow** [comment]
We have some snapshot tests now in `test_renderers.py`!
