### ISSUE TITLE
What happens when interlinks filter is missing from `_quarto.yml`

### ISSUE THREAD

**Issue by hamelsmu** [machow/quartodoc#168]
Test case

- Quarto.yml doesn't have the filter
- User calls `quartdoc {build}` and then `quarto preview` 

Hypothesis: they will see a link that doesn't go anywhere - can we do something about this?  

Solution: we need to enforce the presence of the interlink filter in `_quarto.yml` before we render the site.  We should check in the builder.   

Future -> make the builder part of the preview/rendering process more natively.

**Comment by machow** [comment]
Let's track validating the presence of an interlinks filter in this issue

* https://github.com/machow/quartodoc/issues/259
