### ISSUE TITLE
function docs are rendering extraneous information

### ISSUE THREAD

**Issue by hamelsmu** [machow/quartodoc#194]
See [this repo](https://github.com/hamelsmu/fastcore-quartodoc/tree/main) for a clean repro 

Seems like lots of code is spilling into the rendered description? 👇🏽 

![image](https://github.com/machow/quartodoc/assets/1483922/f0ade1e2-aba0-4f68-bf68-c73719d08b31)

If you run `quartodoc build` followed by `quarto preview` you can see the issue

I can't see any issue off hand why this should happen based on the source code of that particular function that it is throwing up on https://github.com/fastai/fastcore/blob/master/fastcore/basics.py#L147-L151

cc: @machow

**Comment by machow** [comment]
It looks like the docstring has a type in it. It's missing the closing backtick for `` `var_name ``

**Comment by hamelsmu** [comment]
Ok fixing the backtick(https://github.com/fastai/fastcore/pull/530) fixed it, but perhaps we should make quartodoc more resilient towards this

**Comment by hamelsmu** [comment]
This is fixed
