### ISSUE TITLE
Do not re-instantiate griffe loader every time

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#2]
Currently quartodoc has `get_function()`, but the mkdocstrings handlers use an internal variable `._modules_collection` to get other types of objects (e.g. classes, class members?).

E.g. with plotnine

```python
from griffe.loader import GriffeLoader
from griffe.docstrings.parsers import Parser, parse
from griffe.docstrings import dataclasses as ds

griffe = GriffeLoader(docstring_parser = Parser("numpy"))
mod = griffe.load_module("plotnine.geoms")

f_gb = mod._modules_collection["plotnine.geoms.geom_bar.geom_bar"]
```

**Comment by pawamoy** [comment]
If you don't want to access the private attribute `_modules_collection`, you can actually define it and pass it to the loader constructor:

```python
from griffe.loader import GriffeLoader
from griffe.collections import ModulesCollection

collection = ModulesCollection()
loader = GriffeLoader(modules_collection=collection)
loader.load_module("plotnine.geoms")

geom_bar = collection["plotnine.geoms.geom_bar.geom_bar"
```

However note that every object in the Griffe model has the same `__getitem__` method that allows to access members using the dotted-path notation, so an even simpler approach would be:

```python
import griffe

geoms = griffe.load("plotnine.geoms")
geom_bar = geoms["geom_bar.geom_bar"]
```

**Comment by machow** [comment]
Ah, thanks--I'll loop back and make use of these pieces! So far, I've mostly been exploring griffe's dataclasses, which have made the task of visiting / rendering docs so easy :o.

**Comment by machow** [comment]
This has been resolved by a kind of funky move:

* adding a modules_collection argument to `get_object`
* during build, `get_object` is partialed with a modules_collection object

It'd be nice to wire up more naturally to griffe in the future! I'm going to close for now, so I can focus on all the weird high level pieces that go along with rendering docs 😅.
