### ISSUE TITLE
Consolidate Parameter table columns

### ISSUE THREAD

**Issue by schloerke** [machow/quartodoc#208]
If https://github.com/machow/quartodoc/issues/206 is accepted, then I'd like to request that the table columns be combined into `Parameter` and `Description`

If not, I'd like to request that default be before description so everything about the parameter is described as close as possible.

----------------------------------

Current layout:
![Screenshot 2023-06-30 at 12 05 49 PM](https://github.com/machow/quartodoc/assets/93231/41e2c662-f2a8-4451-ae11-f88946c083b4)

Request:
![Screenshot 2023-06-30 at 12 04 47 PM](https://github.com/machow/quartodoc/assets/93231/4ed06f4d-644d-44fe-80e5-f68e26ad8041)

Alternative Request:
![Screenshot 2023-06-30 at 12 09 36 PM](https://github.com/machow/quartodoc/assets/93231/9578ea24-d37f-4920-a50f-daa33a8f62e6)

**Comment by machow** [comment]
Thanks for the suggestion. I definitely think the current number of columns gets in the way (especially on mobile). There's a `_render_table()` method on the renderer. I wonder if that might be a helpful place to experiment on formats for the shiny docs, and then we can think about merging back in a more consolidated table format?

**Comment by schloerke** [comment]
Ah! I keep forgetting I can overwrite all the render methods. 🤦‍♂️ 

I'll submit a PR when something looks nice 😆

**Comment by schloerke** [comment]
This works when we defined custom renderer methods.


Sass updates:
```sass
// Highlight links in code for parameters
code .parameter-annotation a, code .parameter-default a {
  color: $link-color;
}
```

Relevant renderer methods:

```python
    # Consolidate the parameter type info into a single column
    @dispatch
    def render(self, el: ds.DocstringParameter):
        param = f'<span class="parameter-name">{el.name}</span>'
        annotation = self.render_annotation(el.annotation)
        if annotation:
            param = f'{param}<span class="parameter-annotation-sep">:</span> <span class="parameter-annotation">{annotation}</span>'
        if el.default:
            param = f'{param} <span class="parameter-default-sep">=</span> <span class="parameter-default">{el.default}</span>'

        # Wrap everything in a code block to allow for links
        param = "<code>" + param + "</code>"

        clean_desc = sanitize(el.description, allow_markdown=True)
        return (param, clean_desc)

    @dispatch
    def render(self, el: ds.DocstringSectionParameters):
        rows = list(map(self.render, el.value))
        header = ["Parameter", "Description"]

        return self._render_table(rows, header)
```

#### Result

![Screenshot 2023-06-30 at 3 26 10 PM](https://github.com/machow/quartodoc/assets/93231/f8786964-9f7d-4cf8-997a-b90ef19f15cb)

**Comment by schloerke** [comment]
Closing as this deviates from the standard markdown syntax
