### ISSUE TITLE
quartodoc is not compatible w/ pydantic v2

### ISSUE THREAD

**Issue by schloerke** [machow/quartodoc#209]
https://docs.pydantic.dev/2.0/migration/#migration-guide

Related: https://github.com/machow/quartodoc/blob/1375929bc8550b140456f3583e8fa63ffc03e34b/quartodoc/layout.py#L227-L236

**Comment by machow** [comment]
Ah, thanks! It seems pretty tricky to implement root so it's compatible with pydantic v1 and v2 😅. I tried an implementation on this PR, but am now running into another error...

https://github.com/machow/quartodoc/pull/211

```
TypeError: `discriminator` can only be used with `Union` type with more than one variant
```

Seems to occure when  `Page.update_forward_refs()` gets called....

**Comment by machow** [comment]
I wonder if pydantic v2 expects that if there is a discriminator in a Union, then the other elements in the union must also be discriminators?

We have this piece of code...

```python
ContentElement = Annotated[
    Union[Page, Section, Interlaced, Text, Auto], Field(discriminator="kind")
]
"""Entry in the contents list."""

ContentList = list[Union[ContentElement, Doc, _AutoDefault]]
```

Since `Doc` and `_AutoDefault` are just normal pydantic models, maybe it is considering each of them as Unions with only 1 variant?

**Comment by machow** [comment]
Looks like it's this pydantic issue, and resolved in main a couple days ago:

https://github.com/pydantic/pydantic/issues/6339

**Comment by eitsupi** [comment]
Any update on this?
I was going to start using quartodoc but cannot install it because of this problem.

**Comment by mlysy** [comment]
From the pydantic `README` section [Pydantic V1.10 vs. V2](https://github.com/pydantic/pydantic#pydantic-v110-vs-v2):

> Pydantic V2 also ships with the latest version of Pydantic V1 built in so that you can incrementally upgrade your code base and projects: `from pydantic import v1 as pydantic_v1`. 

Might it be a worthwhile first step to just keep the needed bits from V1 until a fully V2 solution is found?

**Comment by machow** [comment]
Oh wow -- I don't know how I missed that, but it seems like a very quick fix, thanks! Given this is way less effort than I was planning, I'll work on making the change this week..!

**Comment by machow** [comment]
This should be resolved in https://github.com/machow/quartodoc/releases/tag/v0.6.4 (thanks to the tip above!)
