### ISSUE TITLE
Using quartodoc build --watch with pyshiny seems to trigger a rebuild loop

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#223]
From pairing with @wch, when we ran `quartodoc build --watch`:

* it did trigger when we changed the source
* after the re-build, another re-build was triggered
* this created an infinite loop of rebuilding

**Comment by machow** [comment]
It looks like the issue may be caused by the watcher including python cache files (e.g. `__pycache__`)

**Comment by hamelsmu** [comment]
I'm looking into this now

**Comment by hamelsmu** [comment]
I cannot repro this issue.  Can you with me repro this?  Steps I tried: 

Install the library and run the command

```
git clone https://github.com/machow/quartodoc.git
pip install -e .
cd docs
quartodoc build --watch
```
In a separate window, I opened `quartodoc/ast.py` and added 

```python
def foo(): pass
```

When I did this, quartodoc did not go into an infinite loop.  I can only guess that the issue might be some kind of idiosycratic thing you are seeing with `__pycache__` in another library which I can try to ignore, but either way it would be great if you could provide an example that was fully reproducible.

**Comment by machow** [comment]
merged!
