### ISSUE TITLE
Add snapshot tests

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#23]
At this point it's probably useful to write a small pytest plugin to replicate https://testthat.r-lib.org/articles/snapshotting.html. I haven't really had the same experience in python 😭 (but could be missing a plugin somewhere?)

**Comment by isabelizimm** [comment]
I use pytest-snapshot https://pypi.org/project/pytest-snapshot/-- it's nothing too fancy, but does the job!

**Comment by machow** [comment]
whoops I duplicated this with #115
