### ISSUE TITLE
Move package configuration completely to pyproject.toml, remove setup.cfg

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#232]
It looks like github dependency graph supports pyproject.toml (and setup.py), but not setup.cfg. Let's move our package configuration there, so we can see who depends on us.

https://github.com/orgs/community/discussions/6456#discussioncomment-5244057

**Comment by machow** [comment]
Plotnine is all on pyproject.toml so might be a good example to look at:

https://github.com/has2k1/plotnine/blob/qdoc/pyproject.toml

**Comment by has2k1** [comment]
> Move our flake8 config into a file called .flake8
> (pyproject.toml not supported: https://github.com/PyCQA/flake8/issues/234#issuecomment-1206730688)

I switched from pyflake/flake8 to [ruff](https://github.com/astral-sh/ruff) and it is wonderful.
