### ISSUE TITLE
Display type values

### ISSUE THREAD

**Issue by schloerke** [machow/quartodoc#237]
Let's say I have the definition
```python
StrFn = Callable[[], str | None]
"""
App-supplied output value function which returns type `str` or `None`
"""
```

When documenting it, I'd like to display the type definition but there isn't any type information available:

```python
quartodoc.ast.preview(el)
#> █─Alias
#> ├─name = 'StrFn'
#> └─annotation = None
```

-------

Expected results: I'd like to display the type definition

**Comment by machow** [comment]
Does using something like below work for getting the code? One challenge is it includes the variable itself (i.e. `StrFn = `), but if you are okay with that, hopefully gives what you want!

### Files

**test_file.py**:

```python
from typing import Callable

StrFn = Callable[[], str | None]
"""
App-supplied output value function which returns type `str` or `None`
"""
```

**test_file2.py**

```python
from test_file import StrFn

```

### Code

```python
from quartodoc import get_object

obj = get_object("test_file2.StrFn")
obj.lines

# Since obj is an alias, it forwards properties to the underlying target
# but you can explicitly get it using .target.
# same result as above
obj.target.lines
```

**Comment by machow** [comment]
Going to close for now, but definitely re-open if you're still hitting this issue
