### ISSUE TITLE
Google-styled docstring support 

### ISSUE THREAD

**Issue by peekxc** [machow/quartodoc#241]
As a feature request, it would be nice if quartodoc supported the more succinct [google-style docstrings](https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings), like [Napoleon](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/) does for Sphinx. Both [seem common](https://stackoverflow.com/questions/3898572/what-are-the-most-common-python-docstring-formats). 

Griffe supports both, though I acknowledge there are some incompatibilities between the two. Indeed, I'm able to do most things with minor changes to the `MdRenderer` just by switching too: 

```python
import yaml
import quartodoc
from quartodoc import Builder, preview, blueprint, collect, MdRenderer
from quartodoc.builder.blueprint import BlueprintTransformer

cfg = yaml.safe_load(open("_quarto.yml", "r"))
builder = Builder.from_quarto_config(cfg)
blueprint = BlueprintTransformer(parser="google").visit(builder.layout)
pages, items = collect(blueprint, builder.dir)
```

I'm not sure if a custom renderer is the correct way to handle this

**Comment by machow** [comment]
Ah, it looks like a [parser option exists](https://github.com/machow/quartodoc/blob/main/quartodoc/autosummary.py#L438), but is currently undocumented. Does something like this work for you?

```yaml
quartodoc:
    parser: "google"
```

Also, if you point me to the repo you're working on, I'm happy to take a look at anything / answer any other questions!

**Comment by peekxc** [comment]
Looks good to me! 

The repo I'm currently trying to build docs for is [here](https://github.com/peekxc/simplextree-py) (main [docs](https://peekxc.github.io/simplextree-py/pages/) + [quartodoc built reference page](https://peekxc.github.io/simplextree-py/pages/reference/SimplexTree.html)). 

Right now I'm using quartodoc's python API (as opposed to the CLI) with google-styled griffe parsing + a custom renderer to render things how I like, though as you can see in the page though Parameters and Returns and Sections are handled fine, I can't run + render examples with quarto yet. I think I'll need to rely more on however `quartodoc` handles this to get the example code working

**Comment by machow** [comment]
Ah, nice! I'm definitely interested in adding approaches to running / inserting example code into docs, so am happy to help!

python examples in docstrings usually use [doctest](https://docs.python.org/3/library/doctest.html) format, like...

```python
	def insert(self, simplices: Iterable[Collection]) -> None:
		"""
		Inserts simplices into the Simplex Tree. 

		Examples:
			>>> st = SimplexTree([range(3)])
			>>> print(st)
			<the literal output text here, for doctest to validate during unit tests>

			>>> st.insert([[0,1]])
			>>> print(st)
			<more literal output text here, for doctest to validate during unit tests>
```

A big challenge with this approach is that sometimes it can be inconvenient to paste the output directly into the docstring. But I wonder if---in the quartodoc renderer---we can hook into the doctest machinery and use it to run the example code?

AFAIK you can run doctest on a single function/class, using something like this

```python
from quartodoc import get_object

def run_doctests_for_a_func(func):
    finder = doctest.DocTestFinder()
    tests = finder.find(func)

    # If there are tests, run them and capture the output
    runner = doctest.DocTestRunner(verbose=False)
    output = []
    for test in tests:
        runner.run(test, out=output.append)
    return ''.join(output)

run_doctests_for_a_func(get_object)
```

There are probably better ways to use `runner.run()`...

**Comment by peekxc** [comment]
So the griffe parsing recognizes the examples section I realized, and just save it as text. I guess I didn't entirely realize I could just write quarto output as is and get what I want... e.g. 

```python
def insert(self, simplices: Iterable[Collection]) -> None:
		"""
		Inserts simplices into the Simplex Tree. 

		Examples:
			```{python}
                        from simplextree import SimplexTree 
                        st = SimplexTree([range(3)])
		        print(st)
                        ```
		        ```{python}
                         st.insert([[0,1]])
			print(st)
			```
```

For some reason I was under the impression that quartodoc was aiming to just render everything under the examples section within a quarto code block (through from these [quartodoc docs](https://machow.github.io/quartodoc/get-started/docstring-examples.html#examples-using-code-blocks) I realize I might be mistaken...) 

So I guess what I was envisioning was more something like light-string parsing directly on the examples section text, e.g.: 

```python
from griffe.docstrings.dataclasses import DocstringSectionExamples
func_obj = get_object('simplextree', 'SimplexTree.insert')
for ds_section in func_obj.docstring.parsed:
  if type(ds_section) == DocstringSectionExamples:
    for i, example_sec in enumerate(ds_section):
      ## Extract text as-is
      ds_txt_kind, ex_text = example_sec.value[0]    

      ## Option (1): wrap all the text within an executable cell
      quarto_cells = '```{python}\n' + ex_text + '```' 

      ## ... or Option (2): split the text using some delimiter to separate outputs, e.g. two newlines, then wrap  
      as_exec_cell = lambda text: '```{python}\n' + text + '\n```'
      quarto_cells = ''.join([as_exec_cell(example) for example in ex_text.split("\n\n")])

      ## Re-assign the text
      ds_section[i].value[1] = quarto_cells 
```

I'm not super familiar with doctest; at the end of the day I just wanted to have nicely rendered example code outputs that users could copy+paste. The first approach achieves this, though at the expense of bloating the raw docstring

**Comment by machow** [comment]
cc @wch @schloerke, curious what y'all think of the above options for executing code in Example sections (or if there's another way you'd want to do things)

**Comment by peekxc** [comment]
Perhaps, as @machow said, both options could be supported. While delimiting the code sections with `>>>` is familiar and doctest friendly, I think there are plenty of situations where not all code cells need have testable text outputs. Code cells that render plots, for example, seem like a huge win for quarto code cells over the doctest format. 

I realize maybe @pawamoy's comment is quite general in that doctest syntax could be _converted_ into quarto code cells, but then I guess syntax mixing may or may not become an issue. 

> since extending the renderer to handle the examples section like above is totally fair game

For now, I think I will tinker around with a custom renderer and see how splitting the lines / wrapping with quarto code cells plays out with larger examples. Admittedly, I'm not sure if this is the "right" way of going about it

**Comment by JanPalasek** [comment]
@machow Just tested it, google style is well supported. Thought the documentation suggests otherwise here: https://machow.github.io/quartodoc/get-started/docstring-style.html

**Comment by machow** [comment]
Thanks for double checking -- I've updated the docs to mention sphinx and google styles can be used! (should update on the deployed docs in a minute or two).

https://github.com/machow/quartodoc/pull/301

I'm going to close this issue for now, but may open another one on executing examples
