### ISSUE TITLE
Add .devcontainer, so we can preview quartodoc in a codespace

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#251]
@hamelsmu is preparing a positconf workshop. It would be handy to have this in quartodoc anyway, since it makes it much easier to walk people through (who may not have quarto installed).

There's a devcontainer in https://github.com/machow/siuba-workshop, using a rocker build, but it seems to be a bit out of date. @hamelsmu pointed out that https://github.com/orgs/quarto-dev/packages?repo_name=quarto-cli is pushing containers.

**Comment by eitsupi** [comment]
> There's a devcontainer in [machow/siuba-workshop](https://github.com/machow/siuba-workshop), using a rocker build, but it seems to be a bit out of date.

Hi, please check the document of the Feature https://github.com/rocker-org/devcontainer-features/tree/main/src/quarto-cli.
We can install any version, so it should not be "a bit out of date".
