### ISSUE TITLE
`quartodoc` is not Auto rendering members

### ISSUE THREAD

**Issue by hamelsmu** [machow/quartodoc#263]
@machow per [the documentation](https://machow.github.io/quartodoc/get-started/basic-content.html#module-and-class-members):

> Documentation for modules and classes can automatically include their members (e.g. class methods and attributes; everything defined inside a module).

If we look at [this branch](https://github.com/machow/quartodoc/blob/members-bug/docs/_quarto.yml#L102-L103) we should expect that all of the members for `MdRenderer` are displayed.  However, this is not the case:

`MdRenderer.signature` is nowhere to be found. 

![image](https://github.com/machow/quartodoc/assets/1483922/772980fd-0238-4d87-9ef2-7a142fda8792)

**Comment by hamelsmu** [comment]
Furthermore, when I change the YAML to 

```
      contents:
        - name: MdRenderer
          children: separate
```

It does NOT render separate pages.

**Comment by machow** [comment]
I see it when running this on main (but might have screwed something up):

```python
import yaml
from quartodoc import Builder, blueprint

cfg = yaml.safe_load("""
quartodoc:
  package: quartodoc
  sections:
    - title: Docstring Renderers
      desc: |
        Renderers convert parsed docstrings into a target format, like markdown.
      options:
        dynamic: true
      contents:
        - name: MdRenderer
""")

builder = Builder.from_quarto_config(cfg)
bp = blueprint(builder.layout)

# 4th entry in members ---
bp.sections[0].contents[0].contents[0].members
```

**Comment by hamelsmu** [comment]
@machow Here is a minimal repro with a slimmed down project https://github.com/hamelsmu/quartodoc-members-repro/tree/main

Also Yes I don't see `signatures` which means something is wrong with the blueprint builder?

```python
import yaml
from quartodoc import Builder, blueprint


cfg = yaml.safe_load("""
quartodoc:
  dir: api
  package: quartodoc
  sidebar: "api/_sidebar.yml"
  sections:
    - title: Docstring Renderers
      options:
        dynamic: true
      contents:
        - name: MdRenderer
""")
bp = blueprint(Builder.from_quarto_config(cfg).layout)
dc = bp.sections[0].contents[0].contents[0]
for m in dc.members:
    print(m.name)
```
Outputs

```
render
render_annotation
render_header
style
summarize
```

My hunch is it has something to do with `dispatch` but its hard to tell

```
   @dispatch
    def signature(self, el: layout.Doc):
        orig = self.display_name

        # set signature path, generate signature, then set back
        # TODO: this is for backwards compatibility with the old approach
        # of only defining signature over griffe objects, which projects
        # like shiny currently extend
        self.display_name = el.signature_name
        res = self.signature(el.obj)
        self.display_name = orig

        return res
```

**Comment by machow** [comment]
Super weird! What version of quartodoc and griffe are you using?

**Comment by hamelsmu** [comment]
quartodoc is latest on master ` 0.6.1.dev2+g52c6d09` , griffe is ` 0.32.3`

**Comment by machow** [comment]
Hmm... it's weird we get different results. If I install quartodoc fresh, so pip list gives...

```
quartodoc                 0.6.1
griffe                    0.32.3
```

I still see signature. Do you mind trying installing from PyPI, in case something else is causing the difference?

**Comment by machow** [comment]
It seems like this might happen due to the include_empty option being set to false by default. In this case, if signature doesn't have a docstring, then the method won't be included. I'm going to close for now, but will keep an eye out for other cases of this happening

https://machow.github.io/quartodoc/get-started/basic-content.html#all-content-options
