### ISSUE TITLE
Hook for doing dynamic things to parse docstrings

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#3]
griffe uses statics analysis to get objects and their docstrings, so some kinds of dynamically generated docstrings won't be found. 

For example:

* siuba uses the `functools.partial` function to define `inner_join` as `partial(join, ...)`.
* plotnine uses a decorator ([`@document`](https://github.com/has2k1/plotnine/blob/main/plotnine/doctools.py#L552)) to fill in common pieces from a template (e.g. [geom_bar](https://github.com/has2k1/plotnine/blob/main/plotnine/geoms/geom_bar.py#L6))
* py-shiny uses a decorator ([`@add_example()`](https://github.com/rstudio/py-shiny/blob/165d698871a4e63f83d0943b881ffb78e89f6f74/shiny/_docstring.py#L25)) for similar reasons (e.g. [isolate](https://github.com/rstudio/py-shiny/blob/main/shiny/reactive/_core.py#L193-L195))

Let's allow a hook for handling these situations at render time:

* `MdRenderer(..., pre_docstring:  Callable[griffe.dataclasses.Object, griffe.dataclasses.Object])`
* user can e.g. get the name off the object, do dynamic work (like import the object directly) and do anything needed like setting the `.docstring` attribute.
* (Alternatively, we could let someone return a string that is the docstring to be parsed?)

**Comment by pawamoy** [comment]
While it's true that the Griffe loader visits code by default instead of using introspection, Griffe also provides a way to load data by actually importing module. Check out the [inspector](https://mkdocstrings.github.io/griffe/reference/griffe/agents/inspector/). Maybe you'll find a way to integrate it in your code flow? Our plan for Griffe is to allow users to selectively choose whether they want to visit or inspect specific objects, but we're not there yet.

**Comment by machow** [comment]
Hey--thanks for the pointer to inspector! I definitely want to integrate as much with griffe (which has been a delight to use!), and am seeing now the flag where the loader can do a dynamic import, and will try that :).

**Comment by pawamoy** [comment]
If you speak about the `allow_inspection` parameter, it won't help you unfortunately, as it's just a switch that says "OK to inspect if sources cannot be found" (typically for builtin and compiled modules). We have yet to add an actual parameter (or some other configuration ability) to say "do inspect even if we found sources".

**Comment by machow** [comment]
Closing, since griffe's dynamic inspection seems like a good path forward!
