### ISSUE TITLE
Have an option not to sort member items.

### ISSUE THREAD

**Issue by has2k1** [machow/quartodoc#318]
Members (when included) of classes and modules are automatically [sorted](https://github.com/machow/quartodoc/blob/678177779eaa5a02fdd74de42c7fe88cdfbf7884/quartodoc/builder/blueprint.py#L399). We should have an option to turn this off. Members especially Attributes can depend on prior members where the order in which they are declared in code matters and therefore it should be preserved in the documentation.

**Comment by machow** [comment]
Thanks for flagging--this makes a lot of sense!

**Comment by gadenbuie** [comment]
I'll second this; sometimes the order doesn't matter technically but is useful when documenting the class. In my case, it's much easier to understand the class fields when they're grouped together, which is broken by alphabetical sorting.

**Comment by machow** [comment]
Should be resolved by #373, and in the v0.8.0 release!
