### ISSUE TITLE
compatibility with griffe 0.45.2

### ISSUE THREAD

**Issue by Moraxyc** [machow/quartodoc#343]
It seems something wrong with [latest griffe 0.45.2](https://pypi.org/project/griffe/)

Reproduce
```
pip install . .[dev]
pytest
```

Pytest report
```
============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-7.4.4, pluggy-1.5.0
configfile: pyproject.toml
testpaths: quartodoc/tests
plugins: anyio-4.4.0, syrupy-4.6.1
collected 150 items

=========================== short test summary info ============================
FAILED quartodoc/tests/test_ast.py::test_preview_warn_alias_no_load - griffe....
FAILED quartodoc/tests/test_builder_blueprint.py::test_func_resolve_alias - g...
============ 2 failed, 146 passed, 2 xfailed, 174 warnings in 9.38s ============
```

**Comment by machow** [comment]
Shoot--thanks for raising. I've raised an issue on the package we use for static analysis, griffe. I think people can avoid this error by using the  colon syntax to refer to objects (`<some>.<module>:<some_object>`). But I think the most common approach is to write `<some>.<module>.<some_object>` with all periods, so it's worth looking into!

https://github.com/mkdocstrings/griffe/issues/283

**Comment by machow** [comment]
Should be resolved in https://github.com/mkdocstrings/griffe/releases/tag/0.45.3
