### ISSUE TITLE
When not rendering interlinks, rendered annotations may contain duplicate names

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#344]
from @r-leyshon

> Hi @machow not sure if this is the most appropriate issue to attach this bug we've found. Do you have any advice?
https://github.com/datasciencecampus/transport-network-performance/issues/280

It looks like `render_interlinks` is not set to True, annotations may duplicate names. For example:

```python
import pathlib

def f(x: pathlib.Path): ...
```

The annotation for x will be `pathlib.pathlib.Path`.

**Comment by r-leyshon** [comment]
Super, thanks for the speedy turnaround! Docs are looking great.
