### ISSUE TITLE
bug: griffe.loader  is not found

### ISSUE THREAD

**Issue by jitingxu1** [machow/quartodoc#357]
had this error
```
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/quartodoc/autosummary.py", line 9, in <module>
    from griffe.loader import GriffeLoader
ModuleNotFoundError: No module named 'griffe.loader'
```
---------------
did some research: 

griffe just released version 1.0.0, which removed all modules under griffe package: https://github.com/mkdocstrings/griffe/releases/tag/1.0.0

**Comment by machow** [comment]
Shoot -- thanks for flagging. I have time this week to take up some quartodoc work, and this is a big priority

**Comment by jitingxu1** [comment]
Thank you so much.

**Comment by machow** [comment]
v0.7.6 should now support griffe v1+. definitely let me know if you run into any issues! (here is the PR: https://github.com/machow/quartodoc/pull/359)
