### ISSUE TITLE
rst function links don't work

### ISSUE THREAD

**Issue by wch** [machow/quartodoc#52]
Examples from https://machow.github.io/quartodoc/examples/shiny/reference/ui.input_slider.html

<img width="302" alt="image" src="https://user-images.githubusercontent.com/86978/222843857-75ca2933-8924-4c39-a05b-7d73e682ea08.png">

<img width="229" alt="image" src="https://user-images.githubusercontent.com/86978/222844111-c7974007-53fa-4092-8870-ef760f9a23a1.png">

**Comment by wch** [comment]
Just a note: we're not necessarily committed to rst-style links, if some other syntax makes sense.

**Comment by machow** [comment]
I have a quick regex for replacing rst links here: https://github.com/machow/quartodoc/blob/main/quartodoc/renderers/base.py#L17

Currently, it's only being used on the See Also section, but we could try applying it over the whole document? (And then switch over the links in the code later?)

**Comment by machow** [comment]
We now attempt to convert all rst interlinks to markdown, which seems to work well
