### ISSUE TITLE
`admonition` marker doesn't work

### ISSUE THREAD

**Issue by wch** [machow/quartodoc#53]
From https://machow.github.io/quartodoc/examples/shiny/reference/ui.input_slider.html

<img width="359" alt="image" src="https://user-images.githubusercontent.com/86978/222844372-06a1d1d4-a073-41cc-a653-5f3ef4df4f28.png">

**Comment by machow** [comment]
I think we will need to change rst directives to markdown (or for MVP simply regex search/replace them?). We should be to apply simple transformations in the [custom shiny renderer](https://github.com/machow/quartodoc/blob/main/examples/shiny/_renderer.py#L32).

For example, by doing something like...

```python
from quartodoc.ast import DocstringSectionNotes

# as a renderer method...

@dispatch
def render(self, el: DocstringSectionNotes):
    result = super().render(el)

    # add some search replace thing
    return re.sub(..., string = result)

```
