### ISSUE TITLE
Should have a way to evaluate variables in docstrings

### ISSUE THREAD

**Issue by wch** [machow/quartodoc#54]
For example, for `update_action_button`, the docstring includes this:

```py

    Note
    ----
    {note}
```

The `{note}` is replaced with a string by a decorator on the function, which looks like this:

```py
_note = "This is a note that is inserted into the docstring of multiple functions."


@doc_format(note=_note)
def update_action_button(
    ...
```

Code here: https://github.com/rstudio/py-shiny/blob/d2eecc35a0ed21ef3d8e1b23dfd28ee09a2a2a6d/shiny/ui/_input_update.py#L73-L104

The resulting output in the Sphinx docs like this (https://shiny.rstudio.com/py/api/reference/shiny.ui.update_slider.html):

<img width="892" alt="image" src="https://user-images.githubusercontent.com/86978/222845025-d306f54a-2bf5-48b4-b5b5-d2f779bdb717.png">

But with quartodoc, it just prints "{note}", probably because the decorator isn't being applied (https://machow.github.io/quartodoc/examples/shiny/reference/ui.update_navs.html):

<img width="409" alt="image" src="https://user-images.githubusercontent.com/86978/222845076-5f4b83a9-dd13-4e97-9074-498e2b8bb501.png">

We don't necessarily have to insert the string at package load time using the `@doc_format` decorator, but we will need to have some way of achieving the same result.

**Comment by machow** [comment]
Working on this right now. I'll add an option for quartodoc to dynamically import the function, and use that docstring.

This way the docstring will be equivalent to...

```python
from shiny.ui import update_action_button

update_action_button.__doc__
```
