### ISSUE TITLE
Top-level pages for sites have odd contents

### ISSUE THREAD

**Issue by wch** [machow/quartodoc#56]
Examples:

https://machow.github.io/quartodoc/examples/shiny/

<img width="864" alt="image" src="https://user-images.githubusercontent.com/86978/222848995-9ce498d7-37da-402b-acd1-20e65c010e4e.png">

*****

https://machow.github.io/quartodoc/examples/pkgdown/ redirects to 
https://machow.github.io/quartodoc/examples/pkgdown/reference/Builder.html

https://machow.github.io/quartodoc/examples/single-page/ redirects to https://machow.github.io/quartodoc/examples/single-page/reference/index.html, which seems reasonable.

**Comment by machow** [comment]
Hey @wch, is this issue about the contents / re-direct behavior of the example sites? Do you have a sense for what a nicer behavior might be?

Because I built the example sites only to show the reference section, I had the examples point there. But happy to adjust to w/e seems nicer!
