### ISSUE TITLE
Quartodoc does not recognize module level docstring

### ISSUE THREAD

**Issue by isabelizimm** [machow/quartodoc#75]
When rendering files with module level docstrings, quartodoc does not render the docstring: ie, something with a docstring [like this](https://github.com/has2k1/mizani/blob/8ce92b4d4ddbb4cfed4eb0fb9af121c9c7fcb6f6/mizani/bounds.py#L1) has the desired output of [being shown on docs](https://mizani.readthedocs.io/en/stable/bounds.html#bounds-limiting-data-values-for-a-palette).

**Comment by machow** [comment]
Hey, thanks for raising! This is implemented in https://github.com/machow/quartodoc/pull/64!

Do you mind sharing an example where you're thinking of using this? Are you wanting it to also automatically render the docstrings for all the functions and classes in the module?

**Comment by isabelizimm** [comment]
Great minds think alike! 😂  I was hoping to add one into vetiver, (on the [BaseHandler, to describe handlers' functionality](https://rstudio.github.io/vetiver-python/latest/reference/BaseHandler.html)). I was imagining the module level docstring appearing as a long-version description under the function/class name, for each function/class in the module. That being said, I am not super committed to that layout, if you had something else in mind!

**Comment by machow** [comment]
This is supported in v3, but labeling to remind myself to include a rendered example of a module doc in our docs.

**Comment by machow** [comment]
This behavior is at least now tested in our snapshot tests! (for example, https://github.com/machow/quartodoc/blob/main/quartodoc/tests/__snapshots__/test_renderers.ambr#L103)
