### ISSUE TITLE
Issues with handling `*args`

### ISSUE THREAD

**Issue by wch** [machow/quartodoc#91]
There are three issues that I've noticed with `*args`.

In Shiny's `navset_pill_list` (https://github.com/rstudio/py-shiny/blob/d036a8aa/shiny/ui/_navs.py#L705-L721):

```
def navset_pill_list(
    *args: NavSetArg,
    id: Optional[str] = None,
    selected: Optional[str] = None,
    header: TagChild = None,
    footer: TagChild = None,
    well: bool = True,
    widths: tuple[int, int] = (4, 8),
) -> NavSet:
    """
    Render nav items as a vertical pillset.
    Parameters
    ----------
    *args
        A collection of nav items (e.g., :func:`shiny.ui.nav`).
     ...
```

Here's a screenshot of the rendered page:

<img width="793" alt="image" src="https://user-images.githubusercontent.com/86978/231242088-dab24f7d-0177-4d6d-8f51-a82eea99d1b9.png">

In the rendered page, the function signature is:

```
ui.navset_pill_list(args, *, id=None, selected=None, header=None, footer=None, well=True, widths=(4, 8))
```

Issue 1: The actual function signature is not `(args, *, id, ...)`. Instead it is `(*args, id, ...)`.

Issue 2: Also, the default value is listed as `()`, but in actuality, there is no default value for the `*args`.

*****

There is a related issue for `page_navbar` (https://github.com/rstudio/py-shiny/blob/main/shiny/ui/_page.py#L26-L48):

```

def page_navbar(
    *args: NavSetArg,
    title: Optional[str | Tag | TagList] = None,
    id: Optional[str] = None,
    selected: Optional[str] = None,
    position: Literal["static-top", "fixed-top", "fixed-bottom"] = "static-top",
    header: Optional[TagChild] = None,
    footer: Optional[TagChild] = None,
    bg: Optional[str] = None,
    inverse: bool = False,
    collapsible: bool = True,
    fluid: bool = True,
    window_title: str | MISSING_TYPE = MISSING,
    lang: Optional[str] = None,
) -> Tag:
    """
    Create a navbar with a navs bar and a title.

    Parameters
    ----------

    args
        UI elements.
```

This is the rendered result:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/86978/231242758-af2746c7-1808-4b4f-a0d5-903d9c9d69ab.png">

Issue 3: The docstring here documents `args` instead of `*args`, and the resulting Qmd file also documents `args` instead of `*args`. I think that quartodoc should flag this as a mistake in the docs -- in the [numpydoc documentation](https://numpydoc.readthedocs.io/en/latest/format.html#parameters), it says that it should be `*args`.

**Comment by machow** [comment]
Function signatures should render this okay now, and the listing of `()` as a default for `*args` is tracked in #112 .
