### ISSUE TITLE
Function links in `See Also` section disappear

### ISSUE THREAD

**Issue by wch** [machow/quartodoc#92]
For example, in `page_navbar` (https://github.com/rstudio/py-shiny/blob/d036a8aaa/shiny/ui/_page.py#L90-L95):

```
    See Also
    -------
    :func:`~shiny.ui.nav`
    :func:`~shiny.ui.nav_menu`
    :func:`~shiny.ui.navset_bar`
    :func:`~shiny.ui.page_fluid`
```

The resulting page looks like this:

<img width="336" alt="image" src="https://user-images.githubusercontent.com/86978/231246924-01494f3c-6a5a-4cae-9a68-39958efc5fe8.png">

The qmd file contains links, but the text is empty. I believe they are double-wrapped in markdown link syntax. This is what it looks like:

```
## See Also

[]([](:func:`~shiny.ui.nav`))
[]([](:func:`~shiny.ui.nav_menu`))
[]([](:func:`~shiny.ui.navset_bar`))
[]([](:func:`~shiny.ui.page_fluid`))
```

I think links like ``[]([](:func:`~shiny.ui.nav`))`` should actually be [](:func:`~shiny.ui.nav`).

Note that it's possible this has something to do with the `_renderer.py` in the pyshiny-site repo.

**Comment by machow** [comment]
This seems to be resolved on the current pyshiny doc site

Here is what I see for [page_navbar](https://shiny.rstudio.com/py/api/ui.page_navbar.html)

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/2574498/231594340-71215a68-10c6-41fa-a4e4-ffc635454445.png">

Please definitely re-open if I missed something important!
